# This is a basic workflow to help you get started with Actions

name: Pull to Remote SSH (For test branch)

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ test ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Apply the change from the remote machine
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.MACHINE_HOST }}
        username: ${{ secrets.MACHINE_USER }}
        key: ${{ secrets.MACHINE_PRIVATE_KEY }}
        script: |
          cd cstodo-test
          git pull
          yarn pm2 restart cstodo-test
